In [162]:
from sklearn.datasets import load_iris
iris = load_iris()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris['data'],
iris['target'], random_state=2409)

Importing iris dataset and spliting it into trainning set and test set

In [163]:
import numpy as np
X = np.genfromtxt("ionosphere.txt", delimiter=",")
X[:3]

array([[ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
         0.83398, -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,
         0.59755, -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,
         0.58212, -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,
         0.56811, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
         0.42267, -0.54487,  0.18641, -0.453  ,  1.     ],
       [ 1.     ,  0.     ,  1.     , -0.18829,  0.93035, -0.36156,
        -0.10868, -0.93597,  1.     , -0.04549,  0.50874, -0.67743,
         0.34432, -0.69707, -0.51685, -0.97515,  0.05499, -0.62237,
         0.33109, -1.     , -0.13151, -0.453  , -0.18056, -0.35734,
        -0.20332, -0.26569, -0.20468, -0.18401, -0.1904 , -0.11593,
        -0.16626, -0.06288, -0.13738, -0.02447, -1.     ],
       [ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
         1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
         0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644

Importing ionosphere from text file

In [164]:
X = np.genfromtxt("ionosphere.txt", delimiter=",",
usecols=np.arange(34))
X[:3]

array([[ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
         0.83398, -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,
         0.59755, -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,
         0.58212, -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,
         0.56811, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
         0.42267, -0.54487,  0.18641, -0.453  ],
       [ 1.     ,  0.     ,  1.     , -0.18829,  0.93035, -0.36156,
        -0.10868, -0.93597,  1.     , -0.04549,  0.50874, -0.67743,
         0.34432, -0.69707, -0.51685, -0.97515,  0.05499, -0.62237,
         0.33109, -1.     , -0.13151, -0.453  , -0.18056, -0.35734,
        -0.20332, -0.26569, -0.20468, -0.18401, -0.1904 , -0.11593,
        -0.16626, -0.06288, -0.13738, -0.02447],
       [ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
         1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
         0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644,
         0.75535, 

In [165]:
y = np.genfromtxt("ionosphere.txt", delimiter=",",
usecols=34, dtype='int')
y[:3]

array([ 1, -1,  1])

In [166]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y, random_state=2409)

Split the dataset into training set and test set

In [167]:
X_train.shape

(112, 4)

In [168]:
X_test.shape

(38, 4)

TEST

In [169]:
import math
def E_len(row1, row2):   
    distance = 0
    for i in range(len(row1)-1):     
        distance += (row1[i] - row2[i])**2
    return math.sqrt(distance)

computing Euclidean distance between two vectors

In [170]:
import math
def get_Neighbour(row1,row2):
    current_n = math.inf
    for n in range(row2.shape[0]):
        dist = E_len(row1,row2[n])
        if dist < current_n:
            current_n = dist
            neighbors = n
        return current_n, neighbors
    # test code to see if it works
get_Neighbour(np.array([1,2,3]),np.zeros((3,3)))

(2.23606797749979, 0)

finds the nearest neighbour to from one to another
implemented using lab 3 but substituting current_min of current n

In [171]:
iris_test = X_test.shape[0]
count = 0
# to count the number of errors 
estimate = np.zeros(iris_test,dtype=int)
for n in range(iris_test):
  estimate[n] = y_train[get_Neighbour(X_test[n],X_train)[1]]
  if estimate[n] != y_test[n]:
    count = count + 1
    print("Error:",n)
print("Errors found:",count)
print("The error rate is",(count / iris_test))

Error: 0
Error: 1
Error: 3
Error: 4
Error: 5
Error: 7
Error: 8
Error: 11
Error: 12
Error: 13
Error: 14
Error: 15
Error: 17
Error: 18
Error: 19
Error: 21
Error: 24
Error: 25
Error: 26
Error: 28
Error: 31
Error: 35
Error: 36
Error: 37
Errors found: 24
The error rate is 0.631578947368421


applying getNeighbors func to test set over each sample

also implemented using lab 3 but intead trainning and for errors

In [172]:
estimate

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

checking the estimates

In [173]:
ion_test = X1_test.shape[0]
# to count the number of errors
count = 0
for n in range(ion_test):

    # define estimate
    estimate = y1_train[get_Neighbour(X1_test[n],X1_test)[1]]
    if estimate != y1_train[n]:
        print("Error:",n)
        count = count + 1
print("Errors found:",count)
print("The error rate is",(count / ion_test))

Error: 1
Error: 3
Error: 7
Error: 9
Error: 11
Error: 12
Error: 14
Error: 17
Error: 19
Error: 20
Error: 23
Error: 24
Error: 26
Error: 28
Error: 30
Error: 31
Error: 33
Error: 34
Error: 36
Error: 39
Error: 41
Error: 48
Error: 49
Error: 52
Error: 53
Error: 55
Error: 59
Error: 67
Error: 68
Error: 69
Error: 70
Error: 74
Error: 75
Error: 81
Error: 82
Error: 87
Errors found: 36
The error rate is 0.4090909090909091


Nearest Neighbour implementation for ionosphere

In [174]:
def conformityPredictor(data,label,n):
  current_n = neighbor = math.inf
  for i in range(data.shape[0]):

        # stores euclidean distance between data to each other
        dist = E_len(data[n],data[i])
        if (dist < current_n) & (label[i]==label[n]) & (i!=n):
          current_n = dist
        if (dist < neighbor) & (label[i]!=label[n]) & (i!=n):
          current_n = dist
        # acts as a base case
        if current_n == 0:
            if (neighbor == 0):
              print("0/0")    
              return 0                 
            return math.inf
  else:
    return neighbor / current_n

    Here we want to test the confomity score of the nth element both the 
    data and the label have been identified and stated use of if condition to find current distance

In [175]:
iris_train = X_train.shape[0]
iris_test = X_test.shape[0]

# the sum of the p values
p_value_count = 0.0
count = 0
# stores the conformity score
conformity_score = np.zeros(iris_train+1)  # the conformity scores
# p-values
p_value = np.zeros(3)
# need to define the type
estimate = np.zeros(iris_test,dtype=int)

for n in range(iris_test):
    # Stack arrays in sequence vertically
    modifiedX = np.row_stack((X_train,X_test[n]))
    for i in range(3): 
        modifiedY = np.append(y_train,i)
        for j in range(iris_train+1):
            conformity_score[j] = conformityPredictor(modifiedX,modifiedY,j)
        # p-value for i 
        p_value[i] = np.mean(conformity_score<=conformity_score[iris_train])  
    estimate[n] = np.argmax(p_value)   
    if estimate[n] != y_test[n]:
        count = count + 1
        print("Error: ",n)


        # adds the sum of p values together
        p_value_count = p_value_count + p_value[0] + p_value[1] + p_value[2] - p_value[y_test[n]]
print("Errors found: ", count)
print("Average false p-value: ", p_value_count/(2*iris_test))

Error:  0
Error:  2
Error:  3
Error:  5
Error:  6
Error:  7
Error:  8
Error:  9
Error:  10
Error:  11
Error:  13
Error:  16
Error:  17
Error:  19
Error:  20
Error:  22
Error:  23
Error:  24
Error:  27
Error:  28
Error:  29
Error:  30
Error:  31
Error:  32
Error:  33
Error:  34
Error:  36
Error:  37
Errors found:  28
Average false p-value:  0.7368421052631579


Conformity predictor for iris
here we calculate and tally up the p values to find an overall sum to help calculate the average p value, whilst also fidning the number of errors detected 

Brief Discussion

In this case we case see that the nearest neighbour and comformity version have 
a different number of errors. Looking at the test sameples the errors are often 
different.